name: Build Android

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop

jobs:
  create-envfile:
    runs-on: ubuntu-latest

    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        directory: .
        file_name: .env
        fail_on_empty: false

  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install app dependencies
        run: npm install

      - name: Add Android platform
        run: cordova platform add android

      - name: Build Android Release APK
        run: cordova build android --release --prod

